"""create shelves table

Revision ID: f35f37c3cd64
Revises: 26c254c0e766
Create Date: 2026-08-13 13:40:29.593475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f35f37c3cd64'
down_revision: Union[str, Sequence[str], None] = '26c254c0e766'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shelves',
    sa.Column('shelf_id', sa.Uuid(), nullable=False),
    sa.Column('shelf_code', sa.String(length=50), nullable=False),
    sa.Column('zone', sa.String(length=50), nullable=False),
    sa.Column('rack', sa.String(length=50), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('max_capacity', sa.Integer(), nullable=False),
    sa.Column('current_capacity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('shelf_id')
    )
    op.create_index(op.f('ix_shelves_shelf_code'), 'shelves', ['shelf_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shelves_shelf_code'), table_name='shelves')
    op.drop_table('shelves')
    # ### end Alembic commands ###
